# Generated by Django 6.0.2 on 2026-02-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='ContatoModel',
        ),
    ]
